services:
  postgres:
    image: postgres:16
    container_name: inventory-postgres
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: servicetemplate.api  
    build:
      context: .
      dockerfile: Sportsbook.InventoryService.API/Dockerfile
    container_name: inventory-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__InventoryDb: "Host=postgres;Port=5432;Database=inventorydb;Username=inventory_user;Password=inventory_pass"
    ports:
      - "5000:8080"
volumes:
  postgres_data:
