<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Behavior\**" />
      <Compile Remove="Mappers\**" />
      <Compile Remove="Services\**" />
      <Compile Remove="Validators\**" />
      <EmbeddedResource Remove="Behavior\**" />
      <EmbeddedResource Remove="Mappers\**" />
      <EmbeddedResource Remove="Services\**" />
      <EmbeddedResource Remove="Validators\**" />
      <None Remove="Behavior\**" />
      <None Remove="Mappers\**" />
      <None Remove="Services\**" />
      <None Remove="Validators\**" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="DotPulsar" Version="3.1.0" />
      <PackageReference Include="FluentValidation" Version="11.8.1" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\InventoryService.Contracts\InventoryService.Contracts.csproj" />
      <ProjectReference Include="..\Sportsbook.InventoryService.Core\Sportsbook.InventoryService.Core.csproj" />
    </ItemGroup>

</Project>
